# install  dependencies and build app
FROM node:16.18 as build
WORKDIR /frontend-react-js
COPY . .
RUN npm install --silent
RUN npm run build

# copy build files and run
FROM nginx:1.16.0-alpine
COPY --from=build /frontend-react-js/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]